### ISSUE TITLE
Question: Why forgo the test directory?

### ISSUE THREAD

**Issue by fearphage** [sinonjs/commons#11]
Just curious why or if there are benefits to this way or downsides to the other? That is all.

**Comment by mroderick** [comment]
There are a few properties of having the tests next to the source file, that I enjoy:

* it is easy to navigate between the source and the test file
    * which makes import/require statements easy
    * it's easy to move files and tests around without breaking things, and you don't have to mirror the folder structure in `test/` as you have in `lib/`
* it is easy to see when the test file is missing

There are also some downsides:

* if you're not careful, you'll put all your tests in the npm packages
* it is NOT following the conventions of mocha
    * this will confuse a few people
    * your test command will have to specify file pattern(s)

These days ESLint allows for overrides for glob patterns, which makes having tests with source a whole lot easier. Before, you'd basically have to have two config files and separate lint commands, or always have your tests in a separate folder, where you could place an extrac `.eslintrc` ... or accept that you'd share settings between source and tests.

I guess it's really just trading one set of conveniences for another set of conveniences. Which one you like more, is probably highly individual.

One feature that I really liked when I worked with Rails (a decade or so ago), was that there's an automagic mapping between source and test files, so the test runner would figure things out for itself. This only worked because of the strict adherence to conventions.

I've been thinking if we could have something similar with mocha, where if a file in `lib/` didn't have a corresponding `.test.js` file either next to it or in `test/`, then the test runner would complain. This is kind of in line with #10, in that exports discovered when the tests are run.

Perhaps I should take a stab at making such a tool, that could be run before/after your test suite ... or maybe @fearphage wants to make such a tool?

**Comment by mgred** [comment]
Serious Question, Nice Explanation.

Personally I also like to write the test/specs next to the corresponding file since it somehow belongs to the source in my opinion.

> I've been thinking if we could have something similar with mocha, where if a file in `lib/` didn't have a corresponding `.test.js` file either next to it or in `test/`, then the test runner would complain. This is kind of in line with #10, in that exports discovered when the tests are run.

Morgan that begs for an eslint plugin, doesn't it?:stuck_out_tongue_winking_eye: I think I will give this a try...

**Comment by mroderick** [comment]
I thought if another downside: sometimes we create test files that exercise the API or track issues, which will not be specific to one file. 

Where do we put that, and what do we call it?

I suppose we could just cram it into whatever tests the “main” file.

**Comment by fearphage** [comment]
> sometimes we create test files that exercise the API or track issues, which will not be specific to one file.
> 
> Where do we put that, and what do we call it?

Well for bugs, I would call the file `bugs/issues.js`. Tests that go across files are not unit tests by definition. Those sound like integration tests. I would make a folder for integration tests and put them there.

> * your test command will have to specify file pattern(s)

You don't have to unless your normal files are weird. Mocha will load files that aren't tests just fine. `mocha lib` works just fine.

**Comment by fearphage** [comment]
> it is easy to navigate between the source and the test file

What does this mean? If you're using a gui, clicking is always easy. From the cli, I generally use something like. `vi lib/file.js test/file.js` or if you want to be fancy (read: type less) `vi {lib,test}/file.js`. It works the same wihen they share directories: `vi lib/file{,.test}.js`. 

> which makes import/require statements easy

We write that once though (generally). So even if it's inconvenient, difficult, or otherwise suboptimal, it's a one-time pain in most cases.

The biggest downside for me is in expectations. I've seen Jest and Golang put tests next to the files, but that's unexpected in a mocha and most javascript project. It's not a huge thing to figure out/work around, but it is something. Just looking at the project (from the base dir), it looks like there are no tests. There's no one location to grep for test and things of that nature. I'm definitely a fan of the `test` directory, but it's mostly about convention and convenience for me. I don't feel super strongly about it. I just wanted to express my thoughts.

**Comment by mroderick** [comment]
> Just looking at the project (from the base dir), it looks like there are no tests

That's a good argument.

However, I think that the `README.md` makes it clear enough that this is a well tested project.

**Comment by mroderick** [comment]
In my most recent open source adventure, I am trying out a hybrid approach:

* Unit tests sit next to the unit they're testing, i.e. in the `lib/` folder.
* Functional tests are in `test/` folder, as they don't concern themselves with individual functions.

https://github.com/mroderick/plete

**Comment by mroderick** [comment]
I think this issue can be closed now
