### ISSUE TITLE
Recent change is breaking our unit tests

### ISSUE THREAD

**Issue by ericuldall** [sinonjs/commons#18]
The recent change you've made https://github.com/sinonjs/commons/commit/cace9e618293337b14fd197d8a87c7e281ef2713
is breaking all of our unit tests that use @sinonjs/commons with the following error:

```
/srv/node_modules/collections/_map.js:162
            return this.size;
                        ^

TypeError: Method get Map.prototype.size called on incompatible receiver #<Map>
    at Map.get size [as size] (<anonymous>)
    at Map.get [as length] (/srv/node_modules/collections/_map.js:162:25)
    at /srv/node_modules/@sinonjs/commons/lib/prototypes/copy-prototype.js:14:29
    at Array.reduce (<anonymous>)
    at copyPrototypeMethods (/srv/node_modules/@sinonjs/commons/lib/prototypes/copy-prototype.js:7:50)
    at Object.<anonymous> (/srv/node_modules/@sinonjs/commons/lib/prototypes/map.js:5:18)
```

Is it possible to revert this change? It's being included by other dependencies and full impact is not known at this point.

**Comment by ericuldall** [comment]
Testing steps:
```
npm list | grep sinon
```
returns @sinonjs/commons is at 1.6.0 and tests are failing

```
rm -rf node_modules/@sinonjs/commons;
npm install @sinonjs/commons@1.4.0
```
After that npm test works again.

**Comment by mroderick** [comment]
I can sympathise with your challenges of having many tests fail because of a dependency update. 

However, cace9e6 is a very unobtrusive change, that shouldn't cause anything to fail.

For the Sinon family of libraries we try our best to avoid clashes with other libraries (which is the motivation for cace9e6), but we can't anticipate that another library would modify the builtin prototypes.

I suspect that the real problem here is that you're using a library that extends the prototypes: https://github.com/montagejs/collections

As a quick fix, you might get lucky with loading `collections` after `@sinonjs/commons` has loaded.

For background, I'd recommend reading:

* https://humanwhocodes.com/blog/2010/03/02/maintainable-javascript-dont-modify-objects-you-down-own/

**Comment by ericuldall** [comment]
I had a ticket open with collections that I've reopened with a link here. We'll see if they have anything good to contribute here.

Also, if anyone else is having this issue and needs a quick fix for now we've just added this to our top level package:

```
"@sinonjs/commons": "1.4.0"
```

Works for now :D

**Comment by nickyang07** [comment]
I also have exactly the same issue. For me, it fails jest. I could not enforce @sinonjs/commons to 1.4.0, since jest fake-timer depends on it. Any other solution?

**Comment by mroderick** [comment]
> I also have exactly the same issue. For me, it fails jest. I could not enforce @sinonjs/commons to 1.4.0, since jest fake-timer depends on it. Any other solution?

Jest and Sinon have been playing well together for years, I'm not sure this is the same issue. Please open a new issue following the issue template and if you can, please provide a runnable example that shows the failure

**Comment by cmyugovic** [comment]
I made it work with:
"sinon": "^7.0.0",
"@sinonjs/commons": "1.4.0",
"nise": "1.5.2"

**Comment by caub** [comment]
What fixes this issue for me if moving `require('sinon')` up to the top of the file
